---
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: aws-lambda-update-function-timeout-1658947438
  namespace: litmus
  creationTimestamp: null
  labels:
    subject: aws-lambda-update-function-timeout_litmus
spec:
  templates:
    - name: custom-chaos

      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
        - - name: lambda-update-function-timeout-mgk
            template: lambda-update-function-timeout-mgk
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: lambda-update-function-timeout-mgk
            path: /tmp/lambda-update-function-timeout-mgk.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Updating timeout allocated to lambda function
                kind: ChaosExperiment
                metadata:
                  name: lambda-update-function-timeout
                  labels:
                    name: lambda-update-function-timeout
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: ci
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - secrets
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: chaosnative/chaos-go-runner:main-latest
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name lambda-update-function-timeout
                    command:
                      - /bin/bash
                    env:
                    - name: TOTAL_CHAOS_DURATION
                      value: '30'
                    - name: CHAOS_INTERVAL
                      value: '30'
                    - name: RAMP_TIME
                      value: ''
                    - name: FUNCTION_NAME
                      value: ''
                    - name: FUNCTION_TIMEOUT
                      value: ''
                    - name: REGION
                      value: ''
                    - name: AWS_SHARED_CREDENTIALS_FILE
                      value: '/tmp/cloud_config.yml'
                    - name: SEQUENCE
                      value: 'parallel'
                    labels:
                      name: lambda-update-function-timeout
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: ci
                    secrets:
                      - name: cloud-secret
                        mountPath: /tmp/

      container:
        name: ""
        image: docker.io/chaosnative/k8s:1.15.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n
            {{workflow.parameters.adminModeNamespace}} && sleep 30

    - name: lambda-update-function-timeout-mgk
      inputs:
        artifacts:
          - name: lambda-update-function-timeout-mgk
            path: /tmp/chaosengine-lambda-update-function-timeout-mgk.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: lambda-update-function-timeout-mgk
                  labels:
                    instance_id: 3b589183-7d6f-402c-835c-6a0638c00b96
                    workflow_name: lambda-update-function-timeout-1658947438
                spec:
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: lambda-update-function-timeout
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: '30'
                            - name: CHAOS_INTERVAL
                              value: '30'
                            - name: FUNCTION_NAME
                              value: ''
                            - name: FUNCTION_TIMEOUT
                              value: ''
                            - name: REGION
                              value: ''
                        probe:
                          - name: healthcheck
                            type: cmdProbe
                            mode: Edge
                            runProperties:
                              probeTimeout: 5s
                              retry: 0
                              interval: 1s
                              stopOnFailure: false
                            cmdProbe/inputs:
                              command: ./healthcheck -name lambda-update-function
                              source:
                                image: chaosnative/chaos-go-runner:main-latest
                                inheritInputs: true
                                volumeMount:
                                  - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                                    name: aws-iam-token
                                    readOnly: true
                                volumes:
                                  - name: aws-iam-token
                                    projected:
                                      defaultMode: 420
                                      sources:
                                        - serviceAccountToken:
                                            audience: sts.amazonaws.com
                                            expirationSeconds: 86400
                                            path: token
                              comparator:
                                type: string
                                criteria: contains
                                value: "[P000]"
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/chaosnative/litmus-checker:1.15.0
        command:
          - ./var/run/checker
        args:
          - -file=/tmp/chaosengine-lambda-update-function-timeout-mgk.yaml
          - -saveName=/tmp/engine-name

    - name: cleanup-chaos-resources
      container:
        name: ""
        image: docker.io/chaosnative/k8s:1.15.0
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (3b589183-7d6f-402c-835c-6a0638c00b96, )' -n
            {{workflow.parameters.adminModeNamespace}} "

  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
