---
name: release

on:
  workflow_dispatch:
    inputs:
#       release_title:
#         description: 'release title'
#         required: true
      release_tag:
        description: 'release tag'
        required: true

jobs:
  create_release:
    name: "create_release"
    runs-on: "ubuntu-latest"
    outputs:
      id: ${{ steps.release-id.outputs.id }}    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
          body: "sample body"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "my first release"
          tag: ${{ github.event.inputs.release_tag }}
