---
name: release

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true

jobs:
  create_release:
    name: "create release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_title }}"
