---
name: release

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true

jobs:
  create_release:
    name: "create_release"
    runs-on: "ubuntu-latest"
    outputs:
      id: ${{ steps.release-id.outputs.id }}    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASEID: ${{ steps.create_release.outputs.id }}
        with:
          args: 'README.md'
          
          
