---
name: release

on:
  workflow_dispatch:
    inputs:   
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true
      release_notes:
        description: 'provide release notes'     
        required: false
        default: ''         

jobs:
  create_release:
    name: "create_release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      
      - name: create release along with artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "binaries/*"
          body: "${{ github.event.inputs.release_title }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "${{ github.event.inputs.release_title }}"
          tag: ${{ github.event.inputs.release_tag }}
