---
name: release

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true

jobs:
  create_release:
    name: "create_release"
    runs-on: "ubuntu-latest"
    outputs:
      id: ${{ steps.release-id.outputs.id }}    
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_title }}"
      - id: set-release-id
        run: echo "::set-output name=release-id::$(curl -s 'https://api.github.com/repos/uditgaurav/logs/releases/latest' | jq -r '.id')"
        
  upload_artifacts:
    needs: [create_release]
    name: upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: 43319757
#          releaseId: ${{ needs.create_release.outputs.id }}          
          args: 'custom/nsutil/nsutil'
          
          
