---
name: AutoRelease

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true


jobs:
  create_release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_title }}"

            
  upload_artifacts:
    name: Upload Artifacts
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: |
            custom/dns_interceptor/dns_interceptor
            custom/pause/pause
