---
name: Component-Pipeline
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
    
defaults:
  run:
    working-directory: /go/src   
      
jobs:

### Setup Litmus

  Setup_Litmus_Infra:
    container: 
      image: "${{ github.event.inputs.e2eTestImage }}"
      volumes:
        - /home/ubuntu/.kube:/root/.kube
        - /etc/kubernetes:/etc/kubernetes
      env:
        OPERATOR_IMAGE: "${{ github.event.inputs.operatorImage }}"
        OPERATOR_NAME: "${{ github.event.inputs.operatorName }}"        
        RUNNER_IMAGE: "${{ github.event.inputs.runnerImage }}"
        IMAGE_PULL_POLICY: "${{ github.event.inputs.imagePullPolicy }}"
        KUBECONFIG: /root/.kube/config
        
    runs-on: [self-hosted,component]
    ## Changing the working directory to image path we provided
    ## As the default path is repository checkout path.      
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: |
          echo "Hello World!!!"
          echo "date +"%T""
