---
name: AutoRelease

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true
  release:
    types: [created]        


jobs:
  create_release:
    name: "create release"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.release_tag }}"
          prerelease: false
          title: "${{ github.event.inputs.release_title }}"

            
  upload_artifacts:
    name: Upload Artifacts
    needs: [create_release]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'custom/dns_interceptor/dns_interceptor'
