---
name: AutoRelease

on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'release title'
        required: true
      release_tag:
        description: 'release tag'
        required: true


jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            custom/dns_interceptor/dns_interceptor
            custom/pause/pause
