---
name: Component-Pipeline
on: workflow_dispatch
    
defaults:
  run:
    working-directory: /go/src   
      
jobs:

### Setup Litmus

  Setup_Litmus_Infra:
        
    runs-on: ubuntu-latest
    ## Changing the working directory to image path we provided
    ## As the default path is repository checkout path.      
    steps:
      - name: Litmus Infra Setup In Cluster-1
        run: |
          echo "Hello World!!!"
          echo "date +"%T""
          echo "Name: {{ secrets.Name }}"
